version: '3.8'

services:
  zeeknet-backend:
    image: ghcr.io/${REGISTRY_OWNER}/zeeknet-backend:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: zeeknet-backend
    restart: always
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PATH=/api
      - VIRTUAL_DEST=/
      - VIRTUAL_PORT=4000
    depends_on:
      - zeeknet-redis
    networks:
      - zeeknet-internal
      - web-network

  zeeknet-frontend:
    image: ghcr.io/${REGISTRY_OWNER}/zeeknet-frontend:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: zeeknet-frontend
    restart: always
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
    networks:
      - web-network

  zeeknet-redis:
    image: redis:alpine
    container_name: zeeknet-redis
    restart: always
    volumes:
      - zeeknet_redis_data:/data
    networks:
      - zeeknet-internal

networks:
  zeeknet-internal:
    driver: bridge
  web-network:
    external: true

volumes:
  zeeknet_redis_data:
