export const TYPES = {
  UserRepository: Symbol.for('UserRepository'),
  CompanyRepository: Symbol.for('CompanyRepository'),
  JobPostingRepository: Symbol.for('JobPostingRepository'),

  CompanyProfileMapper: Symbol.for('CompanyProfileMapper'),
  JobPostingMapper: Symbol.for('JobPostingMapper'),
  UserMapper: Symbol.for('UserMapper'),
  
  PasswordHasher: Symbol.for('PasswordHasher'),
  TokenService: Symbol.for('TokenService'),
  GoogleTokenVerifier: Symbol.for('GoogleTokenVerifier'),
  PasswordResetService: Symbol.for('PasswordResetService'),
  OtpService: Symbol.for('OtpService'),
  MailerService: Symbol.for('MailerService'),
  S3Service: Symbol.for('S3Service'),

  RegisterUserUseCase: Symbol.for('RegisterUserUseCase'),
  LoginUserUseCase: Symbol.for('LoginUserUseCase'),
  AdminLoginUseCase: Symbol.for('AdminLoginUseCase'),
  ForgotPasswordUseCase: Symbol.for('ForgotPasswordUseCase'),
  ResetPasswordUseCase: Symbol.for('ResetPasswordUseCase'),
  VerifyOtpUseCase: Symbol.for('VerifyOtpUseCase'),
  GoogleLoginUseCase: Symbol.for('GoogleLoginUseCase'),
  RefreshTokenUseCase: Symbol.for('RefreshTokenUseCase'),
  LogoutUseCase: Symbol.for('LogoutUseCase'),
  GetUserByIdUseCase: Symbol.for('GetUserByIdUseCase'),

  CreateCompanyProfileUseCase: Symbol.for('CreateCompanyProfileUseCase'),
  UpdateCompanyProfileUseCase: Symbol.for('UpdateCompanyProfileUseCase'),
  GetCompanyProfileUseCase: Symbol.for('GetCompanyProfileUseCase'),
  ReapplyCompanyVerificationUseCase: Symbol.for('ReapplyCompanyVerificationUseCase'),

  CreateJobPostingUseCase: Symbol.for('CreateJobPostingUseCase'),
  GetJobPostingUseCase: Symbol.for('GetJobPostingUseCase'),
  GetCompanyJobPostingsUseCase: Symbol.for('GetCompanyJobPostingsUseCase'),
  GetAllJobPostingsUseCase: Symbol.for('GetAllJobPostingsUseCase'),
  UpdateJobPostingUseCase: Symbol.for('UpdateJobPostingUseCase'),
  DeleteJobPostingUseCase: Symbol.for('DeleteJobPostingUseCase'),
  IncrementJobViewCountUseCase: Symbol.for('IncrementJobViewCountUseCase'),
  UpdateJobStatusUseCase: Symbol.for('UpdateJobStatusUseCase'),

  GetAllUsersUseCase: Symbol.for('GetAllUsersUseCase'),
  BlockUserUseCase: Symbol.for('BlockUserUseCase'),
  AdminGetUserByIdUseCase: Symbol.for('AdminGetUserByIdUseCase'),
  GetAllCompaniesUseCase: Symbol.for('GetAllCompaniesUseCase'),
  GetCompaniesWithVerificationUseCase: Symbol.for('GetCompaniesWithVerificationUseCase'),
  VerifyCompanyUseCase: Symbol.for('VerifyCompanyUseCase'),

  RegistrationController: Symbol.for('RegistrationController'),
  LoginController: Symbol.for('LoginController'),
  TokenController: Symbol.for('TokenController'),
  PasswordController: Symbol.for('PasswordController'),
  AdminController: Symbol.for('AdminController'),
  CompanyController: Symbol.for('CompanyController'),
  CompanyJobPostingController: Symbol.for('CompanyJobPostingController'),
  SeekerController: Symbol.for('SeekerController'),
  OtpController: Symbol.for('OtpController'),
  PublicJobController: Symbol.for('PublicJobController'),

  AppServer: Symbol.for('AppServer'),
  UserBlockedMiddleware: Symbol.for('UserBlockedMiddleware'),
};
